### ISSUE TITLE
can't compile 

### ISSUE THREAD

**Issue by ngx45** [Warfley/PasSimpleSockets#1]
Hi Warfley,

Compile error on Lazarus 2.2.3 (rev lazarus_2_2_2-47-g6c1bc2c78d) FPC 3.2.3 x86_64-linux-gtk2, debian bullseye

----------------------

Hint: (11030) Start of reading config file /home/ngx/gue/laz/fpc/bin/x86_64-linux/fpc.cfg
Hint: (11031) End of reading config file /home/ngx/gue/laz/fpc/bin/x86_64-linux/fpc.cfg
Free Pascal Compiler version 3.2.3-651-g682c53ff6b [2022/07/13] for x86_64
Copyright (c) 1993-2021 by Florian Klaempfl and others
(1002) Target OS: Linux for x86-64
(3104) Compiling udpechoserver.pas
(3104) Compiling /home/ngx/gue/laz/_lib/PasSimpleSockets/simplesockets.pas
..........
/home/ngx/gue/laz/_lib/PasSimpleSockets/simplesockets.pas(348,78) **Error**: (4025) Incompatible type for arg no. 3: Got "^Int64", expected "pSockLen"
/home/ngx/gue/laz/fpc/units/x86_64-linux/rtl-extra/sockets.ppu:unixsock.inc(190,11) **Hint**: (5039) Found declaration: fpaccept(LongInt;psockaddr;pSockLen):LongInt;
/home/ngx/gue/laz/_lib/PasSimpleSockets/simplesockets.pas(382,105) **Error**: (4025) Incompatible type for arg no. 6: Got "^Int64", expected "pSockLen"
/home/ngx/gue/laz/fpc/units/x86_64-linux/rtl-extra/sockets.ppu:unixsock.inc(172,11) **Hint**: (5039) Found declaration: fprecvfrom(LongInt;Pointer;QWord;LongInt;psockaddr;pSockLen):Int64;
/home/ngx/gue/laz/_lib/PasSimpleSockets/simplesockets.pas(529,16) **Error**: (5000) Identifier not found "fp"
/home/ngx/gue/laz/_lib/PasSimpleSockets/simplesockets.pas(529,26) **Fatal**: (2003) Syntax error, ";" expected but "identifier FD_ZERO" found

Fatal: (1018) Compilation aborted

----------------------

On Windows Lazarus 2.2.3 (rev lazarus_2_2_2-47-g6c1bc2c78d) FPC 3.2.3 i386-win32-win32/win64, it works

**Comment by Warfley** [comment]
Should be fixed now
