### ISSUE TITLE
[Shameful Ask]: Implement WriteStrLn and ReadStrLn

### ISSUE THREAD

**Issue by gcarreno** [Warfley/PasSimpleSockets#2]
Hey Frederic (@Warfley),

I could probably pull this off if I dedicate 5 hours to stumble in the dark and then find the solution, but I'm not really that good at sockets and I lack the expertise on sockets and their APIs. So I'm really afraid of introducing inefficiency into the code.

In my opinion you first have to chose between: `CRLF`, `CR` or `LF` and then stick to it no matter the OS's preference on how to terminate a line. I would have to have looksie on how Indy10 implements it's `WriteLn` to a socket just out of curiosity.

Once that's decided, the `WriteStrLn` would only be a call to `WriteStr` with the chosen line termination appended at the end.

Now, the issue is now the `ReadStrLn`... And I see two roads ahead:
1. You do a read on a single byte basis until you hit the line termination and leave the level below to deal with the rest of the buffer.
    - This is where I feel that I would introduce inefficiency.
3. You read in chunks of, let's say 1024, and search for the termination inside those chunks, but now you have the responsibility to manage the buffer.
    - This, from the quick read on the code, would imply a major overhaul to accommodate `SimpleSockets` new management of the buffer.

As you can see, I got the theory or at least the gist of it :smile: 
But then my implementation would be a bit sloppy, or introduce some nasty inefficiencies :disappointed: 

So what do you think?

Cheers,
Gus

**Comment by Warfley** [comment]
You can read data from the buffer without consuming it by using the MSG_PEEK flag. The more pressing issue is that what if there is no newline char? Should it just read all the data that is available and return it, or should it wait (potentially indefenetly) until the newline was read?

A simple example would be this:
```pascal
program client;

{$mode objfpc}{$H+}

uses
  SysUtils, Sockets, SimpleSockets; // order important because simpleSockets redefines TSocket

function PeekAllAvailable(const ASocket: TSocket): String;
var
  readBytes: Integer;
begin
  Result := '';
  readBytes := 0;
  repeat
    if readBytes = Length(Result) then
      SetLength(Result, Length(Result) + 1024);
    readBytes := Receive(ASocket, @Result[1], Length(Result), MSG_PEEK);
  until readBytes < Length(Result);
  SetLength(Result, readBytes);
end;

function ReadTo(const ASocket: TSocket; const Sequence: String; out ReadData: String): Boolean;
var
  Available: String;
  SearchIndex: SizeInt;
begin
  Available := PeekAllAvailable(ASocket);
  SearchIndex := Available.IndexOf(Sequence);
  Result := SearchIndex >= 0;
  if Result then
  begin
    ReadData := ReceiveStr(ASocket, SearchIndex + Sequence.Length); // Consume from buffer
    // Remove sequence from data
    SetLength(ReadData, ReadData.Length - Sequence.Length);
  end;
end;

var
  conn: TSocket;
  Msg: String;
begin
  conn := TCPSocket(stIPv4);
  try
    Connect(conn, '127.0.0.1', 1337);
    while not ReadTo(conn, LineEnding, Msg) do
    begin
      WriteLn('Waiting for data');
      Sleep(1000);
    end;
    WriteLn(Msg);
  finally
    CloseSocket(conn);
  end;
  ReadLn;
end.
```
This will wait until there is data in the buffer containing the sequence. The problem here is that the OS buffer is not infinitely large, so with this method, if the buffer is full, no more data can be received and there will never be a newline in the buffer.

An alternative would be to, if there is no newline, to return the whole data available, and have the program then figure out how to handle this data:
```pascal
program client;

{$mode objfpc}{$H+}

uses
  SysUtils, Sockets, SimpleSockets; // order important because simpleSockets redefines TSocket

function PeekAllAvailable(const ASocket: TSocket): String;
var
  readBytes: Integer;
begin
  Result := '';
  readBytes := 0;
  repeat
    if readBytes = Length(Result) then
      SetLength(Result, Length(Result) + 1024);
    readBytes := Receive(ASocket, @Result[1], Length(Result), MSG_PEEK);
  until readBytes < Length(Result);
  SetLength(Result, readBytes);
end;

function ReadTo(const ASocket: TSocket; const Sequence: String; out ReadData: String): Boolean;
var
  Available: String;
  SearchIndex: SizeInt;
begin
  Available := PeekAllAvailable(ASocket);
  SearchIndex := Available.IndexOf(Sequence);
  Result := SearchIndex >= 0;
  if Result then
  begin
    ReadData := ReceiveStr(ASocket, SearchIndex + Sequence.Length); // Consume from buffer
    // Remove sequence from data
    SetLength(ReadData, ReadData.Length - Sequence.Length);
  end else // No sequence in buffer: Consume all
    ReadData := ReceiveStr(ASocket, Available.Length);
end;

var
  conn: TSocket;
  Msg, MsgPart: String;
  Found: Boolean;
begin 
  Msg := '';
  Found := False;
  conn := TCPSocket(stIPv4);
  try
    Connect(conn, '127.0.0.1', 1337);
    repeat
      if not DataAvailable(conn, 1000) then
      begin
        WriteLn('Waiting for data or parts');
        Continue;
      end;
      Found := ReadTo(conn, LineEnding, MsgPart);
      Msg += MsgPart;
      if not Found then
        WriteLn('Waiting for full data, part received: ', MsgPart);
    until Found;
    WriteLn(Msg);
  finally
    CloseSocket(conn);
  end;
  ReadLn;
end.
```
As you can see, as this always consumes the buffer, it has the advantage of being able to use DataAvailable (which in the other apporach wouldn't work because the data in the buffer is never consumed)

**Comment by Warfley** [comment]
I've added some new functionality, first there is now `BytesAvailable(Socket)` which returns the number of bytes that are currently in buffer, as well as if the buffer size in RecvStr is no < 0 then it will read the whole buffer (same for ReceiveArray). This simplifies above code to
```pascal
function ReadTo(const ASocket: TSocket; const Sequence: String; out ReadData: String): Boolean;
var
  Available: String;
  SearchIndex: SizeInt;
begin
  // Available := PeekAllAvailable(ASocket); No need for PeekAllAvailable function anymore, can now be done with ReceiveStr
  Available := ReceiveStr(ASocket, -1, MSG_PEEK);
  [...]
```

I will not add the specific ReadTo function as described above, the handling of what shall happen if the sequence is not available is not clear, so I leave it up to the user to build such a function themselves

**Comment by gcarreno** [comment]
Hey Frederic (@Warfley),

Thank you very much for the code examples and the suggestions on how to pull of the Sequence Terminated String Read!!!
I'll have a look at your code with a better eye and I'll do my best to do it :smiley: 

With regards to your, **very valid and pertinent**, question about what happens when there is **NO** Sequence coming/in the buffer/sent, I would have to answer:
I'm not sure since I haven't had the opportunity to look how Indy solves this issue.

In my opinion, this should not be a problem for the implementer. This responsibility should shift onto the user of the implementation. I say this because if you're gonna use `ReadLN`, you should be using `WriteLN`.

The only thing that comes to mind is if or when there's some kind of error and the Sequence is lost in transit.
Then were in trouble cuz it's never gonna show up :smile: 

Still, to give you a better informed answer I would have to look at how Indy pulls it off !!

Cheers,
Gus
