### ISSUE TITLE
Not finding `ioctlsocket` and `FIONREAD` when compiling under Linux

### ISSUE THREAD

**Issue by gcarreno** [Warfley/PasSimpleSockets#3]
Hi @Warfley,

looks like we have a smidge of an issue :smile: :
```
./simplesockets/simplesockets.pas(586,6) Error: (5000) Identifier not found "ioctlsocket"
./simplesockets/simplesockets.pas(586,30) Error: (5000) Identifier not found "FIONREAD"
simplesockets.pas(600) Fatal: (10026) There were 2 errors compiling module, stopping
```
This is for the latest(trunk) and 2 early stable versions: 2.0.12 and 2.2.2.

I've done a search and `ioctlsocket` is really only present under Windows, or am I wrong?

Cheers,
Gus

**Comment by gcarreno** [comment]
Hey @Warfley,

Got it compiling again under Linux by changing `BytesAvailable` to:
```pas
function BytesAvailable(const ASocket: TSocket): SizeInt;
{$IFDEF WINDOWS}
var
  count: DWord;
{$IFEND}
begin
  Result := -1;
{$IFDEF WINDOWS}
  if ioctlsocket(ASocket.FD, FIONREAD, @count) = 0 then
    Result := Count;
{$IFEND}
end;
```

I know it's not the correct thing to do, but it'll scratch my itch for the time being...

I'll let you come up with a more permanent solution!!

Cheers,
Gus

**Comment by Warfley** [comment]
Now part of FCL-net and issue fixed
